# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-tuantn"
BBFILE_PATTERN_meta-tuantn = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-tuantn = "6"

LAYERDEPENDS_meta-tuantn = "core"
LAYERSERIES_COMPAT_meta-tuantn = "dunfell"
